name: photosphere
version: 0.0.1
description: A mobile-friendly web app with routing, responsive CSS, and (optional) Sass support.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  route_hierarchical: '>=0.5.0 <0.7.0'
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=1.0.0 <2.0.0'
  vector_math: any
transformers:
- script_inliner
